In [3]:
import duckdb
import pandas as pd
import os
from datetime import datetime

In [4]:
con = duckdb.connect(database='dados_duckdb.db', read_only=False)

In [26]:
arquivo = 'z0019_2.csv'
data_ingestao = datetime.now()
df = pd.read_csv(f'../landing/{arquivo}',sep=';')
df['nome_arquivo'] = arquivo
df['data_ingestao'] = data_ingestao
df.head()

   NATBR    MAKTX WERKS  MAINS  LABST nome_arquivo              data_ingestao
0  10004    SERRA  BT50    100    200  z0019_2.csv 2026-03-14 15:09:14.698371
1  10005  MACHADO  BT50    100    100  z0019_2.csv 2026-03-14 15:09:14.698371
2  10003    PREGO  BT10    100     60  z0019_2.csv 2026-03-14 15:09:14.698371

In [27]:
con.execute( """
    CREATE TABLE IF NOT EXISTS bronze_produtos (
        NATBR VARCHAR,
        MAKTX VARCHAR,
        WERKS VARCHAR,
        MAINS VARCHAR,
        LABST VARCHAR,
        nome_arquivo VARCHAR,
        data_ingestao TIMESTAMP
    )
""")

In [28]:
con.execute("INSERT INTO bronze_produtos SELECT * from df")

In [33]:
resultado = con.execute("SELECT * FROM bronze_z0019").fetch_df()
resultado.head(6)

   NATBR     MAKTX WERKS MAINS LABST nome_arquivo              data_ingestao
0  10001  PARAFUSO  BT10   100   100  z0019_1.csv 2026-03-14 15:02:34.262019
1  10002   MARTELO  BT50   100  1500  z0019_1.csv 2026-03-14 15:02:34.262019
2  10003     PREGO  BT10   100    50  z0019_1.csv 2026-03-14 15:02:34.262019
3  10004     SERRA  BT50   100   200  z0019_2.csv 2026-03-14 15:09:14.698371
4  10005   MACHADO  BT50   100   100  z0019_2.csv 2026-03-14 15:09:14.698371
5  10003     PREGO  BT10   100    60  z0019_2.csv 2026-03-14 15:09:14.698371

In [31]:
con.execute("ALTER TABLE bronze_produtos RENAME  TO bronze_z0019")

In [34]:
con.close()